name: Commit Date
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create report file
        run: date +%s > report.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Actions
          author_email: Actions@GitHub.com
          message: 'Your commit message'
          add: 'report1.txt'
